from __future__ import annotations

import html

from .models import ReasoningSession

CSS = """
:root { color-scheme: light dark; }
body {
  font: 14px/1.5 -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  max-width: 920px;
  margin: 2em auto;
  padding: 0 1em;
  color: #1d1d1f;
  background: #ffffff;
}
@media (prefers-color-scheme: dark) {
  body { color: #f5f5f7; background: #111; }
  h2, .kv dt, footer { color: #aaa; }
  .check, .thought, pre { background: #1b1b1d; }
}
h1 { font-size: 1.6em; margin: 0 0 0.5em; }
h2 { font-size: 1.1em; margin: 1.5em 0 0.3em; color: #444; border-bottom: 1px solid #ddd; padding-bottom: 0.2em; }
.verdict { display: inline-block; padding: 0.4em 0.9em; border-radius: 4px; font-weight: 700; letter-spacing: 0.04em; text-transform: uppercase; font-size: 0.85em; }
.verdict-block { background: #fee; color: #b00020; }
.verdict-warn { background: #fff8e1; color: #946200; }
.verdict-approve { background: #e8f5e9; color: #2e7031; }
.kv { display: grid; grid-template-columns: 180px 1fr; gap: 0.3em 1em; margin: 0.5em 0; }
.kv dt { color: #666; }
.check { padding: 0.5em 0.8em; margin: 0.3em 0; border-left: 3px solid #ddd; background: #fafafa; border-radius: 2px; }
.check.pass { border-color: #2e7031; }
.check.warn { border-color: #b58900; background: #fffbe6; color: #1d1d1f; }
.check.block { border-color: #b00020; background: #fff5f5; color: #1d1d1f; }
.check-name { font-weight: 700; font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: 0.9em; }
.evidence { color: #555; font-size: 0.9em; margin-top: 0.3em; padding-left: 0.8em; border-left: 2px solid #ddd; }
pre { background: #f5f5f7; padding: 0.8em; border-radius: 4px; overflow: auto; font-size: 0.9em; white-space: pre-wrap; }
.thought { background: #f8f9fb; padding: 0.8em; margin: 0.5em 0; border-radius: 4px; }
.thought-num { color: #888; font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: 0.85em; }
.unit { border-left: 2px solid #14ded2; margin: 0.5em 0 0.5em 1em; padding: 0.4em 0 0.4em 0.8em; }
.unit-meta { color: #777; font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: 0.82em; }
.constraint { color: #555; font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: 0.85em; }
footer { margin-top: 3em; padding-top: 1em; border-top: 1px solid #ddd; color: #888; font-size: 0.85em; }
"""


def render_trace_html(session: ReasoningSession) -> str:
    preflight = session.preflight
    classification = preflight.classification

    checks_html = "\n".join(
        f'<div class="check {_esc(check.status)}">'
        f'<span class="check-name">{_esc(check.name)}</span> - '
        f"<span>{_esc(check.detail)}</span>"
        + (
            f'<div class="evidence">{"<br>".join(_esc(evidence) for evidence in check.evidence)}</div>'
            if check.evidence
            else ""
        )
        + "</div>"
        for check in preflight.checks
    )

    thoughts_html = "\n".join(_render_step(step) for step in session.steps)
    if not thoughts_html:
        thoughts_html = "<p><em>No reasoning steps recorded.</em></p>"

    blocks_html = _list(preflight.blocks)
    warnings_html = _list(preflight.warnings)
    decomposition_html = _render_decomposition(preflight.decomposition) if preflight.decomposition else ""

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Rulence Trace - {_esc(session.session_id)}</title>
<style>{CSS}</style>
</head>
<body>
<h1>Rulence Trace</h1>
<div class="verdict verdict-{_esc(preflight.verdict)}">{_esc(preflight.verdict)}</div>

<h2>Task</h2>
<pre>{_esc(session.task)}</pre>

<h2>Classification</h2>
<dl class="kv">
  <dt>Tier</dt><dd>{_esc(classification.label)}</dd>
  <dt>Policy</dt><dd>{_esc(preflight.policy.ref)}</dd>
  <dt>Session</dt><dd>{_esc(session.session_id)}</dd>
  <dt>Status</dt><dd>{_esc(session.status)}</dd>
</dl>

{f"<h2>Blocks</h2>{blocks_html}" if preflight.blocks else ""}
{f"<h2>Warnings</h2>{warnings_html}" if preflight.warnings else ""}

<h2>Checks</h2>
{checks_html}

{f"<h2>Decomposition</h2>{decomposition_html}" if decomposition_html else ""}

<h2>Reasoning Steps</h2>
{thoughts_html}

<footer>Generated by Rulence - local-first agent governance.</footer>
</body>
</html>
"""


def _render_step(step) -> str:
    meta = f"Thought {step.thought_number}/{step.total_thoughts}"
    if step.is_revision:
        meta += f" (revision of {step.revises_thought})"
    if step.branch_id:
        meta += f" (branch {_esc(step.branch_id)} from {step.branch_from_thought})"
    return f'<div class="thought"><div class="thought-num">{meta}</div><div>{_esc(step.thought)}</div></div>'


def _render_decomposition(dag) -> str:
    summary = (
        f"<dl class=\"kv\">"
        f"<dt>Method</dt><dd>{_esc(dag.method)}</dd>"
        f"<dt>Root units</dt><dd>{len(dag.root_units)}</dd>"
        f"<dt>Flat units</dt><dd>{len(dag.flat)}</dd>"
        f"<dt>Max depth</dt><dd>{_esc(dag.max_depth_reached)}</dd>"
        f"</dl>"
    )
    units = "".join(_render_unit(unit) for unit in dag.root_units)
    return summary + units


def _render_unit(unit) -> str:
    deps = f" depends_on={list(unit.depends_on)}" if unit.depends_on else ""
    applies = f" applies_to={list(unit.applies_to)}" if unit.applies_to else ""
    constraints = "".join(
        f'<div class="constraint">{_esc(constraint.kind)}({_esc(constraint.condition)}, {_esc(constraint.target)})</div>'
        for constraint in unit.constraints
    )
    children = "".join(_render_unit(child) for child in unit.children)
    return (
        '<div class="unit">'
        f'<div class="unit-meta">{_esc(unit.id)} T{_esc(unit.tier)} {unit.polarity} verb={_esc(unit.verb)}{_esc(deps)}{_esc(applies)}</div>'
        f"<div>{_esc(unit.instruction)}</div>"
        f"{constraints}{children}"
        "</div>"
    )


def _list(values: tuple[str, ...]) -> str:
    return "<ul>" + "".join(f"<li>{_esc(value)}</li>" for value in values) + "</ul>"


def _esc(value: object) -> str:
    return html.escape(str(value) if value is not None else "")
